Add encryption feature
Soreepeong/CmdXivLauncher pull request #1
Opened 2021-06-26 18:27 UTC by tkiapril

For those who use password managers without functionality to execute custom commands.

2021-07-06 04:18 UTC, Soreepeong commented on README.md
> +* user[+p[+..]],(text|json),(path or - for stdout)[,passphrase][;user[+p[+..],..]]
Need some examples, including descriptions on what would each example do.

2021-07-07 07:47 UTC, Soreepeong requested changes

2021-07-07 07:47 UTC, Soreepeong commented on xivlogin.py
> +* user[+p[+..]],(text|json),(path or - for stdout)[,passphrase][;user[+p[+..],..]]
^

2021-07-07 07:47 UTC, Soreepeong commented on README.md
> +* user[+p[+..]],(text|json),(path or - for stdout)[,passphrase][;user[+p[+..],..]]
Need some examples, including descriptions on what would each example do.

2021-07-27 14:56 UTC, tkiapril commented on xivlogin.py
> +* user[+p[+..]],(text|json),(path or - for stdout)[,passphrase][;user[+p[+..],..]]
Done!

2021-07-27 14:56 UTC, tkiapril commented on README.md
> +* user[+p[+..]],(text|json),(path or - for stdout)[,passphrase][;user[+p[+..],..]]
Done!

2021-07-27 16:42 UTC, merged